name: CustomGUI
version: '1.0-SNAPSHOT'
main: com.uplineservers.customGUI.CustomGUI
api-version: '1.21'
authors: [ Emanuel Scura ]
website: https://emanuelscura.me
description: Advanced custom GUI API for Minecraft plugins

depend: []
softdepend: []

commands:
  guitest:
    description: Opens the test GUI
    usage: /<command> [menu|trash|storage|display|action]
    permission: customgui.use
    permission-message: You do not have permission to use this command
  guiinfo:
    description: Displays information about the custom GUI plugin
    usage: /<command>
    permission: customgui.info
    permission-message: You do not have permission to use this command