name: UplineGuiApi
version: '${version}'
main: com.uplineservers.uplineguiapi.UplineGuiApi
api-version: '26.2'
authors: [ Emanuel Scura ]
website: https://emanuelscura.me
description: Advanced custom GUI API for Minecraft plugins

commands:
  uplineguiapi:
    description: Main command for UplineGuiApi plugin
    aliases: [ uplinegui ]
    usage: /<command> <test|info> [option]
    permission: uplinegui.use
    permission-message: You do not have permission to use this command
