name: CustomGUI
version: '1.0-SNAPSHOT'
main: com.uplineservers.customGUI.CustomGUI
api-version: '1.21'
authors: [ Emanuel Scura ]
website: https://emanuelscura.me
description: Advanced custom GUI API for Minecraft plugins

depend: []
softdepend: []

commands:
  guitest:
    description: Opens the test GUI
    usage: /<command>
    permission: customgui.use
    permission-message: You do not have permission to use this command
  guihelp:
    description: Displays help for the custom GUI command
    usage: /<command>
    permission: customgui.help
    permission-message: You do not have permission to use this command